databases:
  - name: route53-clone-db
    databaseName: route53clone
    user: route53user
    plan: free

services:
  - type: web
    name: route53-clone-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: route53-clone-db
          property: connectionString

